version: '2'
services:
  web:
    build: .
    container_name: web
    environment:
      - APP_ENV=development
    ports:
      - "8080:8080"
    volumes:
      - "./:/go/src/github.com/synnick/go-playground"
